Update the Github Actions workflow.
Making it match the RMG-Py workflow more closely.
Using setup-miniconda action.
Splitting job into parts.
Better management of dual PRs that need a different RMG-Py branch.
Rename the deploy.sh to trigger-rmg-tests.sh

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -3,32 +3,60 @@ name: CI
 on: [push]
 
 jobs:
-  build-linux:
+  build-and-test-linux:
     runs-on: ubuntu-latest
     strategy:
       max-parallel: 5
-
+    env: # update this if needed to match a pull request on the RMG-database
+      RMG_PY_BRANCH: master
+    defaults:
+      run:
+        shell: bash -l {0}
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python 3.7
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.7
-    - name: Add conda to system path
-      run: |
-        # $CONDA is an environment variable pointing to the root of the miniconda directory
-        echo $CONDA/bin >> $GITHUB_PATH
-    - name: Install dependencies and run unittests
-      run: |
-        cd ..
-        git clone https://github.com/ReactionMechanismGenerator/RMG-Py.git
-        cd RMG-Py
-        conda env create -q -f environment.yml
-        source activate rmg_env
-        conda list
-        git clone -b arkanepy3 https://github.com/mjohnson541/Q2DTor.git external/Q2DTor
-        make
-        make test-unittests
-        make test-functional
-        make test-database
-        
+      - uses: actions/checkout@v2
+      - name: Get RMG-Py source code
+        run: |
+          cd ..
+          git clone -b $RMG_PY_BRANCH https://github.com/ReactionMechanismGenerator/RMG-Py.git
+          cd RMG-Py
+          git clone -b arkanepy3 https://github.com/mjohnson541/Q2DTor.git external/Q2DTor
+      - uses: conda-incubator/setup-miniconda@v2
+        with:
+          environment-file: ../RMG-Py/environment.yml
+          python-version: 3.7
+          activate-environment: rmg_env
+      - name: Conda info
+        run: |
+          conda info
+          conda list
+      - name: Install MOPAC
+        env:
+          MOPACKEY: ${{ secrets.MOPACKEY }}
+        timeout-minutes: 1
+        continue-on-error: true # allowed to fail on pull request from a forked repository
+        run: |
+          set +o pipefail
+          yes 'Yes' | ${CONDA_PREFIX}/bin/mopac "$MOPACKEY"
+      - name: Compile RMG
+        run: |
+          cd ../RMG-Py
+          make
+      - name: Trigger RMG-tests
+        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/stable' }} # only push events to branches other than master and stable
+        env:
+          GH_TOKEN: ${{ secrets.RMG_DEV_TOKEN }}
+        run: ./trigger-rmg-tests.sh
+      - name: Unit tests
+        run: |
+          cd ../RMG-Py
+          make test-unittests
+      - name: Functional tests
+        if: ${{ success() || failure() }} # Run even if the unit tests failed (but not if they were cancelled)
+        run: |
+          cd ../RMG-Py
+          make test-functional
+      - name: Database tests
+        if: ${{ success() || failure() }} # Run even if the functional tests failed (but not if they were cancelled)
+        run: |
+          cd ../RMG-Py
+          make test-database
